# apiVersion: v1
# kind: Service
# metadata:
#   name: service-name-frontend
# spec:
#   selector:
#     pod-label-key-app: pod-label-value-frontend
#   ports:
#     - protocol: TCP
#       containerPort: 80
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ui
# spec:
#   selector:
#     version: v2.0.0
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
---
  apiVersion: v1
  kind: Service
  metadata:
    name: ui
    
  spec:
    type: NodePort
    selector:
      app: frontend
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
