apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      initContainers:
      - name: initbox
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "cat /etc/nginx/conf.d/default.conf && sleep 40"]
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        command: ["/bin/sh"]
        args: ["-c","nginx -g 'daemon off;'"]
        livenessProbe:
          failureThreshold: 10
          # exec:
          #   command: 
          #     - ls
          #     - /etc/nginx/conf.d/default.conf
          
          # httpGet:
          #   path: /
          #   port: 80
          # initialDelaySeconds: 0
          # timeoutSeconds: 10
          # periodSeconds: 5