# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   #name: name of deployment
#   name: nginx
#   labels:
#     #deploy-label-key-app: deploy-label-value-nginx
#     app: nginx
# spec:
#   selector:
#     matchLabels:
#       #pod-label-key-app: pod-label-value-nginx
#       app: nginx
#   template:
#     metadata:
#       labels:
#         #pod-label-key-app: pod-label-value-nginx
#         app: nginx
#     spec:
#       terminationGracePeriodSeconds: 0
#        #restartPolicy: Never #not allowed
#       containers:
#       - name: nginx
#         image: nginx:1.17-alpine
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   replicas: 1 #change to 4
#   strategy:
#     rollingUpdate:
#       maxSurge: 50%
#       maxUnavailable: 0%
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       name: nginx
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.17-alpine #toggl 1.16-alpine
# ---
# # pod is scheduled and scaled as a unit. 
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   #replicas: 2
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       name: nginx
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.17-alpine
#         resources:
#           limits:
#             memory: 50Mi #change to high value
#       - name: busybox
#         image: busybox
#         command: ["/bin/sleep","100"]