apiVersion: v1
kind: Pod 
metadata:
 name: pod-name
 labels:
   label-key-app: label-value
spec:
  containers:
  - name: container-name
    image: nginx:1.17-alpine
---
apiVersion: v1
kind: Pod 
metadata:
 name: nginx
 labels:
   app: nginx
spec:
  restartPolicy: Never
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:1.17-alpine
---
apiVersion: v1
kind: Pod 
metadata:
 name: nginx
 labels:
   app: nginx
spec:
  restartPolicy: Never
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:1.17-alpine
    command: ["/bin/echo"]
    args: ["strongest avenger"]
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  restartPolicy: Never
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:1.17-alpine
    
    #image: nginx:117-alpine
    
    command: ["/bin/echo-m"]
    args: ["strongest avenger"]
    
    #command: ["/bin/bash"]
    #args: ["test.sh"]
    
    # env:
    #   - name: STRONGEST_AVENGER
    #     value: incredible_hulk   
    # command: ["/bin/sh"]
    # args: ["-c", "if [ -z \"$STRONGEST_AVENGER\" ]; then echo \"nobody\"; exit 1; else echo \"$STRONGEST_AVENGER\"; fi"]
---
apiVersion: v1
kind: Pod 
metadata:
 name: nginx
 labels:
   app: nginx
spec:
  restartPolicy: Never
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:1.17-alpine
    command: ["/bin/echo"]
    args: ["strongest avenger"]
    resources:
      requests:
        memory: 50Mi
        cpu: 25
      limits:
        memory: 100Mi
        cpu: 20
---