apiVersion: v1
kind: Pod 
metadata:
 #name: pod-name
 name: nginx
 labels:
   #label-key-app: label-value
   app: nginx
spec:
  #terminationGracePeriodSeconds: 0
  containers:
  #- name: container-name
  - name: nginx
    image: nginx:1.17-alpine
---
# apiVersion: v1
# kind: Pod 
# metadata:
#  name: nginx
#  labels:
#    app: nginx
# spec:
#   #restartPolicy: Never
#   terminationGracePeriodSeconds: 0
#   containers:
#   - name: nginx
#     image: nginx:1.17-alpine
#     command: ["/bin/sh"]
#     args: ["-c","sleep 3 && echo \"sleep timer over\""]
# ---
# apiVersion: v1
# kind: Pod 
# metadata:
#  name: nginx
#  labels:
#    app: nginx
# spec:
#   restartPolicy: Never
#   terminationGracePeriodSeconds: 0
#   containers:
#   - name: nginx
#     image: nginx:1.17-alpine #change to wrong image
#     command: ["/bin/echo"] #change to wrong invocation
#     args: ["strongest evenger"] #change to wrong arguments
# ---
# apiVersion: v1
# kind: Pod 
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   restartPolicy: Never
#   terminationGracePeriodSeconds: 0
#   containers:
#   - name: nginx
#     image: nginx:1.17-alpine
#     env:
#       - name: STRONGEST_AVENGER
#         value: incredible_hulk   
#     command: ["/bin/sh"]
#     #args: ["-c", "if [ -z \"$STRONGEST_AVENGER\" ]; then echo \"nobody\" > /dev/termination-log; exit 1; else echo \"$STRONGEST_AVENGER\"; fi"]
#     args: ["-c", "if [ -z \"$STRONGEST_AVENGER\" ]; then echo \"nobody\"; exit 1; else echo \"$STRONGEST_AVENGER\"; fi"]
# ---
# apiVersion: v1
# kind: Pod 
# metadata:
#  name: nginx
#  labels:
#    app: nginx
# spec:
#   restartPolicy: Never
#   terminationGracePeriodSeconds: 0
#   containers:
#   - name: nginx
#     image: nginx:1.17-alpine
#     command: ["/bin/echo"]
#     args: ["strongest avenger"]
#     resources:
#       requests:
#         memory: 50Mi
#         cpu: 25
#       limits:
#         memory: 100Mi
#         cpu: 20
# ---