apiVersion: v1
kind: Pod
metadata:
  name: evict
  labels:
    app: evict 
  namespace: kube-system
spec:
  priorityClassName: system-node-critical
  terminationGracePeriodSeconds: 0
  containers:
  - name: evict
    imagePullPolicy: IfNotPresent
    image: busybox
    resources:
      requests:
        memory: "2740Mi"
        cpu: "250m"
      limits:
        memory: "3000Mi"
        cpu: "500m"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"hello\"; sleep 2; done"]
    